# Generated by Django 5.2.4 on 2025-07-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('titles', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('google_map_link', models.URLField()),
                ('freelance', models.BooleanField(default=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
