# Generated by Django 5.2.4 on 2025-07-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enquiry_service_skills_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bio',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
