# Generated by Django 5.2.4 on 2025-07-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bio_cover_image_bio_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='summery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
